language: generic

sudo: required
services:
  - docker

before_install:
  - docker build  -t vikashsurin/docker-react-travis -f Dokcerfile.dev  .

script:
  - docker run -e CI=true vikashsurin/docker-react-travis npm run test
